# Generated by Django 2.0.7 on 2023-10-13 05:35

from django.db import migrations, models
import employee_dir.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='employee_id',
            field=models.PositiveIntegerField(default=employee_dir.models.generate_employee_id, unique=True),
        ),
    ]
